# -*- coding: utf-8 -*-
"""python-basico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13DV9yNrO5cDOhjEuXHPrxXCCysRB14fg

# **Introdução à Linguagem Python - Básico**

**Comando de Escrita - print()**
"""

variavel = "BRUNO"
print("Texto exibido na tela para o usuário " + variavel)
print("Análise de Algoritmos é a melhor disciplina")
print("O palmeiras não têm mundial!")
print("Digite um número inteiro positivo: ")

"""**Exemplo de váriaveis**"""

variavel = 12
variavel = 5.19
variavel = "Bruno"
variavel = ["Maça", "Uva", "Morango"]
variavel = True

#Exibindo o valor da variavel
print(variavel)

"""**Exemplo tipos de dados - Conversão**"""

#Especificar tipo da variável
variavel = int(12)
variavel = float(5.19)
variavel = str("Bruno")
variavel = list(["Maça", "Uva", "Morango"])
variavel = bool(True)

#Exibindo o valor da variavel
print(variavel)

"""**Comando de Leitura - input**"""

#Realizando a entrada de dado por parte do usuário
nome = input("Digite seu nome: ")

#Exibindo o dado inserido pelo usuário
print("Olá, seu nome é " + nome)

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")
altura = float(input("Digite sua altura: "))
print("Olá, seu nome é " + nome + ", possui " + idade + " anos e sua altura é " + str(altura))
novaIdade = int(idade) + 1
print(novaIdade)

"""**Comandos de Atribuição**"""

soma = 10
soma = soma + 22
soma = soma + 177
soma = soma + 53
soma = soma - 2
soma = soma * 2
soma = soma + 10

print("SOMA = " + str(soma))

"""**Exemplo Operadores Aritmeticos**"""

a = int(input("Digite um número a: "))
b = int(input("Digite um número b: "))

resultado = a * b
print(str(a) + " * " + str(b) + " = " + str(resultado))
resultado = a / b
print(str(a) + " / " + str(b) + " = " + str(resultado))
resultado = a % b
print("Resto da divisão de " + str(a) + " por " + str(b) + " = " + str(resultado))
resultado = a ** b
print(str(a) + " elevado a " + str(b) + " = " + str(resultado))

"""**EXEMPLO 1:** Construa um programa em Python, que dado uma temperatura em graus Fahrenheit, converta essa temperatura para graus Celsius, sabendo que: C=(𝐹 −32)∗5/9"""

fah = float(input("Digite uma temperatura em Fahrenheit: "))

#cel = (fah - 32.0) * (5.0 / 9.0)
print("A temperatura em graus celsius = " + str((fah - 32.0) * (5.0 / 9.0)))

"""**Comandos de Seleção**

**Exemplo 2:** Dado um número inteiro positivo x, verifique se esse número é PAR ou ÍMPAR.
"""

x = int(input("Digite um número inteiro: "))

if x % 2 == 0 :
    print("O número é PAR!")
    print("PARRRRR")
else :
    print("O número é ÍMPAR!")

"""**Exemplo 3:** Dado um número inteiros positivo (x), indique se ele pertence ao intervalo [0, 100]."""

x = int(input("Digite um número inteiro positivo: "))

if x >= 0 and x <= 100:
    print(str(x) + " pertence ao intevalo!")
else:
    print(str(x) + " não pertence ao intevalo!")

"""**Exemplo 4:** Faça um código em Python que, dado a nota da prova 1 (NP1) e a nota da prova 2 (NP2), calcule a média final (MF) de um aluno e indique se ele foi APROVADO ou REPROVADO, sabendo que:
* M𝐹=(𝑁𝑃1+𝑁𝑃2)/2
* Se MF >= 5,0 APROVADO,
* Se MF >= 3,0 E MF < 5,0 EXAME
* Senão REPROVADO
"""

NP1 = float(input("Digite a nota da prova 1: "))
NP2 = float(input("Digite a nota da prova 2: "))

MF = (NP1 + NP2) / 2.0
if MF >= 5.0:
    print("APROVADO!")
elif MF >= 3.0 and MF < 5.0:
    print("EXAME!")
else:
    print("REPROVADO!")

"""**Comados de Repetição**

**Exemplo 5:** Dado um número inteiro positivo n, imprimir os n primeiros números inteiros positivos.
"""

n = int(input("Digite um número inteiro: "))

numAtual = 1
while numAtual <= n:
    print(str(numAtual) + ", ")
    numAtual += 1

"""**Exemplo 7:** Dado um número inteiro positivo n, imprimir todos os números pares entre 0 e n. Imprima também a quantidade de números pares identificados."""

n = int(input("Digite o valor de n: "))

qtdPar = 0
numAtual = 0
while numAtual <= n:
    if numAtual % 2 == 0:
        print("Número par: " + str(numAtual))
        qtdPar += 1
    numAtual += 1

print("Quantidade de n° pares: " + str(qtdPar))